ALTER TABLE "DigestItem"
  ADD COLUMN "citationUrls" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "platform" TEXT NOT NULL DEFAULT 'Web',
  ADD COLUMN "publishedAt" TIMESTAMP(3),
  ADD COLUMN "evidence" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "uncertainty" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "followUp" TEXT NOT NULL DEFAULT '';
