-- InterestTag is introduced by the later 20260808_interest_memory_a1 migration.
-- Keep this historical migration as a no-op so an empty database can apply the
-- dependency chain in order. The adjacency table and backfill follow in
-- 20260816_interest_adjacency_repair after its prerequisite tables exist.
